name: lint

on:
  commit:
    branches: [master]
      - '**'
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: make lint
        with:
          my_id: ${{ secrets.DENIS_ID }} 
